apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  # labels:
  #   app: db
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10-alpine
          ports:
            - containerPort: 5432
              name: db
